### ISSUE TITLE
Broken META.json

### ISSUE THREAD

**Issue by bence98** [pmqs/Compress-Raw-Zlib#29]
`"abstract"` and `"author"` are set to `"unknown"`, please fix it in `Makefile.PL` and `META.{json,yml}`

Also, the latter two are generated by Makefile.PL, so doesn't that mean they should be `.gitignore`d?

**Comment by bence98** [comment]
`CPANPLUS::Dist::Arch`. It sets the package description to `"unknown"` as a result. Plus, as per the META.json specification version 1.2, these two fields are required (literally the first two fields in the list).

https://metacpan.org/pod/CPAN::Meta::Spec#REQUIRED-FIELDS

**Comment by pmqs** [comment]
> `CPANPLUS::Dist::Arch`. It sets the package description to `"unknown"` as a result. Plus, as per the META.json specification version 1.2, these two fields are required (literally the first two fields in the list).
> 
> https://metacpan.org/pod/CPAN::Meta::Spec#REQUIRED-FIELDS

Don't have a problem setting those keys, but I've have those setting for a VERY VERY long time without any issue. Does `CPANPLUS::Dist::Arch`fail with these set to `unknown`?
