### ISSUE TITLE
See AUTHOR doesn't contain the stated information

### ISSUE THREAD

**Issue by benkasminbullock** [pmqs/Compress-Raw-Zlib#5]
https://metacpan.org/pod/Compress::Raw::Zlib#DESCRIPTION

says

see "AUTHOR" for details about where to get zlib

but it doesn't contain the stated information:

AUTHOR
This module was written by Paul Marquess, pmqs@cpan.org.

**Comment by pmqs** [comment]
The details for zlib are in the **SEE ALSO** section. POD updated

**Comment by pmqs** [comment]
Issue fixed in bf5a03c1b440c8d9e41cffb344bf889794cc532b
